she_codes_news/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name='story'),
    path('add-story/', views.AddStoryView.as_view(), name='newStory'),
]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
]

she_codes_news/users/urls.py
from django.urls import path
from .views import CreateAccountView
from .views import AccountView

app_name = 'users'

urlpatterns = [
    path('create-account/', CreateAccountView.as_view(), name='createAccount'),
    path('<int:pk>/', AccountView.as_view(), name= 'user')
]

she_codes_news/news/models.py
from django.contrib.auth import get_user_model
from django.db import models

USER = get_user_model()

class NewsStory(models.Model):
    title = models.CharField(max_length=200)
    # author = models.CharField(max_length=200)
    author = models.ForeignKey(
        USER, on_delete=models.CASCADE
    )
    pub_date = models.DateTimeField()
    content = models.TextField()
    image_url = models.URLField(max_length=200, default='https://img.freepik.com/premium-photo/astronaut-outer-open-space-planet-earth-stars-provide-background-erforming-space-planet-earth-sunrise-sunset-our-home-iss-elements-this-image-furnished-by-nasa_150455-16829.jpg')

she_codes_news/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    pass

    def __str__(self):
        return self.username

she_codes_news/news/forms.py
from django import forms
from django.forms import ModelForm
from .models import NewsStory

class StoryForm(ModelForm):
    class Meta:
        model = NewsStory
        fields = ['title', 'pub_date', 'image_url', 'content']

        widgets = {
            'pub_date': forms.DateInput(format=('%m/%d/%Y'), 
            attrs={'class':'form-control', 'placeholder':'Select a date','type':'date'}),
        }

she_codes_news/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email']

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email']

she_codes_news/news/views.py
from django.views import generic
from django.urls import reverse_lazy
from .models import NewsStory
from .forms import StoryForm


class IndexView(generic.ListView):
    template_name = 'news/index.html'

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all().order_by('-pub_date')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['all_stories'] = self.get_queryset()
        context['latest_stories'] = context['all_stories'][:4]
        
        return context  

class StoryView(generic.DetailView):
    model = NewsStory
    template_name = 'news/story.html'
    context_object_name = 'story'

class AddStoryView(generic.CreateView):
    form_class = StoryForm
    context_object_name = 'storyForm'
    template_name = 'news/createStory.html'
    success_url = reverse_lazy('news:index')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

she_codes_news/users/views.py
from django.shortcuts import render

from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views import generic
from .models import CustomUser
from .forms import CustomUserCreationForm

class CreateAccountView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/createAccount.html'

class AccountView(generic.DetailView):
    model = CustomUser
    template_name = 'users/accountView.html'
    context_object_name = 'user'

she_codes_news/news/templates/news/createStory.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel='stylesheet' type='text/css' href="{% static 'news/styles.css' %}">
{% endblock%}

{% block content %}

{% if request.user.is_authenticated %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="submit">
    </form>
{% comment %} {% else %}
    <p> Please <a href="{% url 'login' %}">login</a> or <a href="{% url 'users:createAccount' %}">create account</a> to create story.</p> {% endcomment %}

{% endif %}

{% endblock %}

she_codes_news/news/templates/news/index.html
    {% extends "base.html" %}
    {% load static %}

    {% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
    {% endblock %}

    {% block content %}

    {% if request.user.is_authenticated %}
        <div class="welcome">
            <a>Welcome back {{ user.username }} <span>&#128075;</span></a>
            {% comment %} <a href="{% url 'news:newStory' %}">Add New Story</a> {% endcomment %}
            <a href="{% url 'news:newStory' %}" target="_parent"><button>Add New Story!</button></a>    
        </div>

    {% else %}
        {% comment %} <p> Please <a href="{% url 'login' %}">login</a> or <a href="{% url 'users:createAccount' %}">create account</a> to create story.</p> {% endcomment %}
    {% endif %}

    <h2>Latest News</h2>

    <div id="latest-stories">
        {% if latest_stories %}
            {% for story in latest_stories %}
                {%include "./storyCard.html" with story=story position=forloop.counter %}
                <!-- <p>{{ story.title }}</p> -->
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

    <h2>All News</h2>
    <div id="all-stories">
        {% if latest_stories %}
            {% for story in all_stories %}
                {% include "./storyCard.html" with story=story %}
                <!-- <p>{{ story.title }}</p> -->
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

    {% endblock %}

she_codes_news/news/templates/news/story.html
{% extends 'base.html' %}

{% load static %}

{% block stylesheets %}
<link rel='stylesheet' type='text/css' href="{% static 'news/styles.css' %}">
{% endblock%}
{% block content %}
<div>
  <h2>{{ story.title }}</h2>
  <h4>{{ story.author }}</h4>
  <div id="story-content">
    <img src="{{story.image_url}}"/>
    {{ story.content|linebreaks }}
  </div>
</div>
{% endblock %}

she_codes_news/news/templates/news/storyCard.html
<div class="story-card" id="story-card-{{ position }}">
    <a href="{% url 'news:story' story.id %}">
      <img src="{{ story.image_url }}"/>
      <div class="story-card-text">
        <h3>{{ story.title }}</h3>
        <h4>{{ story.author }}</h4>
        <h4>{{ story.pub_date }}</h4>
      </div>
    </a>
</div> 

she_codes_news/templates/base.html
{% load static %}
<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>She Codes News</title>
        <meta name="description" content="">
        <meta name="author" content="Ellen">
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
        {% block stylesheets %}{% endblock %}
    </head>

    <body>
        <header>
            <div id="header-text">
                <a id="header-link" href="{% url 'news:index' %}">
                    <h1 style="color:#8246af">She<span style="color: #f9a427">{Codes} News</span></h1>
                </a>
            </div>
            <div id="nav">
                {% include './nav.html' %}
            </div>
        </header>

        <!-- content blocks here -->
    {% block content %}{% endblock %}
    </body>
</html>

she_codes_news/templates/nav.html
{% comment %} {% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
{% endcomment %}


<nav>
    <a href="{% url 'news:index' %}">Home</a>
    {% if request.user.is_authenticated %}
        {% comment %} <a href="{% url 'users:user' pk=user.id %}">{{ user.username }}</a> {% endcomment %}
        <a href="{% url 'users:user' pk=user.id %}">Profile</a>
        {% comment %} <a href="{% url 'news:newStory' %}">Add Story</a> {% endcomment %}
        <a href="{% url 'logout' %}">Logout</a>
    {% else %}
        <a href="{% url 'login' %}">Login</a>
        <a href="{% url 'users:createAccount' %}">Sign up</a>
    {% endif %}
</nav>

she_codes_news/users/templates/users/accountView.html
{% extends "base.html" %}

{% block content %}

<div>
    <h2>Account Profile</h2>
    <h2>{{user.username}}</h2>
    <h4>Email: {{user.email}}</h4>
    <h4>Last login: {{ user.last_login }}</h4>
    <h4>Date joined: {{user.date_joined}}</h4>
</div>

{% endblock %}

she_codes_news/users/templates/users/createAccount.html
{% extends 'base.html' %}

{% block content %}
<h2>Create Account</h2>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create Account</button>
</form>
{% endblock content %}